### ISSUE TITLE
Building issue on Windows platform

### ISSUE THREAD

**Issue by WilliamHF** [stephank/node-libalac#5]
The lib apparently fails to npm install on a Windows platform with bitutilities / binding definitions ?

\node_modules\libalac\ALAC\codec\ALACBitUtilities.h(68): error C2371: 'ELEMENT_TYPE'
..\binding.cc(124): error C2131  [\node_modules\libalac\build\binding.vcxproj]

**Comment by m-a-v** [comment]
The problem is that ELEMENT_TYPE is already defined in winioctl.h.

**Comment by m-a-v** [comment]
There is another problem. Array of variable length are not supported. binding.cc:124 could be replaced with:

current: char cookie[cookieSize];
new: char\* cookie = (char*)alloca(sizeof(char) \* (cookieSize));

**Comment by EraYaN** [comment]
I just get syntax errors (a lot of them)

```
> libalac@0.1.2 install C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac
> node-gyp rebuild


C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  EndianPortable.c
  ALACBitUtilities.c
  ag_dec.c
  ag_enc.c
  dp_dec.c
  dp_enc.c
  matrix_dec.c
  matrix_enc.c
..\ALAC\codec\dp_dec.c(47): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_dec.c(48): error C2085: 'sign_of_int' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_enc.c(66): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_dec.c(48): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_enc.c(67): error C2085: 'sign_of_int' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_enc.c(67): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\dp_dec.c(132): warning C4013: 'sign_of_int' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxp
roj]
..\ALAC\codec\dp_enc.c(141): warning C4013: 'sign_of_int' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxp
roj]
  win_delay_load_hook.c
..\ALAC\codec\ag_enc.c(65): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(66): error C2085: 'lead' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(91): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(66): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(92): error C2085: 'lead' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(81): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(92): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(82): error C2085: 'lg3a' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(107): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(82): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(108): error C2085: 'lg3a' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(91): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(108): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(92): error C2085: 'abs_func' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(117): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(92): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(118): error C2085: 'read32bit' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(101): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(118): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(102): error C2085: 'read32bit' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(136): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(102): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(137): error C2085: 'getstreambits' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(115): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(137): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(116): error C2085: 'dyn_code' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(171): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(116): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(172): error C2085: 'dyn_get' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(151): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(172): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(152): error C2085: 'dyn_code_32bit' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(220): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(152): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(221): error C2085: 'dyn_get_32bit' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(187): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(221): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(188): error C2085: 'dyn_jam_noDeref' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(188): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(299): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(211): error C2054: expected '(' to follow 'inline' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(305): warning C4013: 'lg3a' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(212): error C2085: 'dyn_jam_noDeref_large' : not in formal parameter list [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxpro
j]
..\ALAC\codec\ag_dec.c(310): warning C4013: 'dyn_get_32bit' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vc
xproj]
..\ALAC\codec\ag_enc.c(212): error C2143: syntax error : missing ';' before '{' [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(315): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\buil
d\binding.vcxproj]
..\ALAC\codec\ag_dec.c(333): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(284): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(336): warning C4013: 'lead' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(287): warning C4013: 'lg3a' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_dec.c(339): warning C4013: 'dyn_get' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(297): warning C4013: 'abs_func' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj
]
..\ALAC\codec\ag_dec.c(341): warning C4018: '<=' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(300): warning C4013: 'dyn_code_32bit' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.v
cxproj]
..\ALAC\codec\ag_enc.c(302): warning C4013: 'dyn_jam_noDeref' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.
vcxproj]
..\ALAC\codec\ag_enc.c(304): warning C4013: 'dyn_jam_noDeref_large' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\bi
nding.vcxproj]
..\ALAC\codec\ag_enc.c(328): warning C4018: '<=' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(330): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(335): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(354): warning C4013: 'lead' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj]
..\ALAC\codec\ag_enc.c(357): warning C4013: 'dyn_code' undefined; assuming extern returning int [C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac\build\binding.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Erwin\AppData\Roaming\npm\node_modules\nodetunes\node_modules\alac2pcm\node_modules\libalac
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodetunes" "-g"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! libalac@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libalac@0.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libalac package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libalac
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

```

I know I CAN build packages, because mdns builds fine. (I tried installing nodetunes)

Node version is 0.12.9
Windows version is 8.1 x64 (latest/current)
VS 2013 version is: 12.0.40629.00 Update 5 (it's ultimate so it should have all required features)

**Comment by m-a-v** [comment]
I was able to compile it using VS 2015 Community Edition ... but Airsonos wasn't accepted by iTunes as AirPlay device. I only succeeded to compile it on Ubuntu with microadam's nodetunes patch and was able to use it with iTunes.

https://github.com/m-a-v/airsonos

which depends on:
https://github.com/m-a-v/node-libalac
https://github.com/m-a-v/nodetunes (version of microadam)

I don't remember the Node version i used.
Windows version is 10 x64 (latest/current)
VS 2015 Community Edition

**Comment by EraYaN** [comment]
microadams version seems to be merged upstream.

Added pull-request with a fix for the errors above #6

**Comment by m-a-v** [comment]
I didn't remember anymore that microadams was merged upstream but I noticed that I didn't use the microadam version mentioned above.

I tried it to recompile with VS 2015 and Node 0.12.9 (x64) with success. But only if I append "--no-bin-links".

**Comment by m-a-v** [comment]
I get the following error when building without --no-bin-links. Anyone can help me?

39186 verbose unlock done using C:\Users\Username\AppData\Roaming\npm-cache_locks\airsonos-f94f1b5423456247.lock for C:\Users\Username\AppData\Roaming\npm\node_modules\airsonos
39187 verbose stack Error: ENOENT, chmod 'C:\Users\Username\AppData\Roaming\npm\node_modules\airsonos\bin\index.js'
39187 verbose stack     at Error (native)
39188 verbose cwd C:\Users\Username\node_modules\airsonos
39189 error Windows_NT 10.0.10586
39190 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/m-a-v/airsonos" "-g"
39191 error node v0.12.9
39192 error npm  v2.14.9
39193 error path C:\Users\Username\AppData\Roaming\npm\node_modules\airsonos\bin\index.js
39194 error code ENOENT
39195 error errno -4058
39196 error enoent ENOENT, chmod 'C:\Users\Username\AppData\Roaming\npm\node_modules\airsonos\bin\index.js'
39196 error enoent This is most likely not a problem with npm itself
39196 error enoent and is related to npm not being able to find a file.
39197 verbose exit [ -4058, true ]

**Comment by indown** [comment]
the same issues

**Comment by stephank** [comment]
Sorry, this is unmaintained. I will archive the repository now.
